// OHADA Compta — Plan Comptable SYSCOHADA Revise & SYCEBNL
// Conforme aux normes OHADA — Acte Uniforme relatif au droit comptable

const SYSCOHADA_CLASSES = [
  { num: 1, label: "Comptes de ressources durables", color: "#C8922A", type: "Bilan", sens: "Credit" },
  { num: 2, label: "Comptes d'actif immobilise", color: "#448AFF", type: "Bilan", sens: "Debit" },
  { num: 3, label: "Comptes de stocks", color: "#18FFFF", type: "Bilan", sens: "Debit" },
  { num: 4, label: "Comptes de tiers", color: "#FF9100", type: "Bilan", sens: "Variable" },
  { num: 5, label: "Comptes de tresorerie", color: "#00E676", type: "Bilan", sens: "Debit" },
  { num: 6, label: "Comptes de charges des activites ordinaires", color: "#FF5252", type: "Gestion", sens: "Debit" },
  { num: 7, label: "Comptes de produits des activites ordinaires", color: "#00E676", type: "Gestion", sens: "Credit" },
  { num: 8, label: "Comptes des autres charges et produits", color: "#a78bfa", type: "Gestion", sens: "Variable" },
  { num: 9, label: "Contributions volontaires en nature (SYCEBNL)", color: "#64FFDA", type: "Gestion", sens: "Variable" },
];

const PLAN_COMPTABLE_SYSCOHADA = [
  // Classe 1
  {numero:"10",libelle:"Capital",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"101",libelle:"Capital social",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"1011",libelle:"Capital souscrit, appele, verse",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"1012",libelle:"Capital souscrit non appele",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"1013",libelle:"Capital souscrit appele non verse",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"11",libelle:"Reserves",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"111",libelle:"Reserve legale",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"112",libelle:"Reserves statutaires",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"113",libelle:"Reserves reglementees",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"118",libelle:"Autres reserves",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"12",libelle:"Report a nouveau",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"121",libelle:"Report a nouveau crediteur",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"129",libelle:"Report a nouveau debiteur",classe:1,type:"Bilan",sens:"Debit"},
  {numero:"13",libelle:"Resultat net de l'exercice",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"131",libelle:"Resultat net: Benefice",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"139",libelle:"Resultat net: Perte",classe:1,type:"Bilan",sens:"Debit"},
  {numero:"14",libelle:"Subventions d'investissement",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"141",libelle:"Subventions d'equipement",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"16",libelle:"Emprunts et dettes assimilees",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"161",libelle:"Emprunts obligataires",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"162",libelle:"Emprunts aupres des etablissements de credit",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"163",libelle:"Avances recues de l'Etat",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"164",libelle:"Avances et acomptes recus sur commandes",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"165",libelle:"Depots et cautionnements recus",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"166",libelle:"Interets courus",classe:1,type:"Bilan",sens:"Credit"},
  {numero:"168",libelle:"Autres emprunts et dettes",classe:1,type:"Bilan",sens:"Credit"},
  // Classe 2
  {numero:"21",libelle:"Immobilisations incorporelles",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"211",libelle:"Frais de developpement et de prospection",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"212",libelle:"Brevets, licences, logiciels",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"213",libelle:"Concessions et droits similaires",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"214",libelle:"Fonds commercial et droit au bail",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"218",libelle:"Autres immobilisations incorporelles",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"22",libelle:"Terrains",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"221",libelle:"Terrains agricoles et forestiers",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"222",libelle:"Terrains nus",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"223",libelle:"Terrains batis",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"224",libelle:"Travaux de mise en valeur des terrains",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"23",libelle:"Batiments, installations techniques et agencements",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"231",libelle:"Batiments industriels, agricoles, administratifs",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"232",libelle:"Batiments affectes aux autres activites",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"233",libelle:"Ouvrages d'infrastructure",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"234",libelle:"Installations techniques",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"235",libelle:"Amenagements de bureaux",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"238",libelle:"Autres installations et agencements",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"24",libelle:"Materiel",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"241",libelle:"Materiel et outillage industriel et commercial",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"242",libelle:"Materiel et outillage agricole",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"243",libelle:"Materiel d'emballage recuperable",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"244",libelle:"Materiel de bureau et informatique",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"245",libelle:"Materiel de transport",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"246",libelle:"Immobilisations animales et agricoles",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"248",libelle:"Autres materiels",classe:2,type:"Bilan",sens:"Debit"},
  {numero:"28",libelle:"Amortissements",classe:2,type:"Bilan",sens:"Credit"},
  {numero:"281",libelle:"Amortissements des immobilisations incorporelles",classe:2,type:"Bilan",sens:"Credit"},
  {numero:"282",libelle:"Amortissements des terrains",classe:2,type:"Bilan",sens:"Credit"},
  {numero:"283",libelle:"Amortissements des batiments",classe:2,type:"Bilan",sens:"Credit"},
  {numero:"284",libelle:"Amortissements du materiel",classe:2,type:"Bilan",sens:"Credit"},
  // Classe 3
  {numero:"31",libelle:"Marchandises",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"311",libelle:"Marchandises A",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"312",libelle:"Marchandises B",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"32",libelle:"Matieres premieres et fournitures liees",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"321",libelle:"Matieres A",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"322",libelle:"Matieres B",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"33",libelle:"Autres approvisionnements",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"331",libelle:"Matieres consommables",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"332",libelle:"Fournitures d'atelier et d'usine",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"333",libelle:"Fournitures de magasin",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"334",libelle:"Fournitures de bureau",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"35",libelle:"Produits finis",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"351",libelle:"Produits A",classe:3,type:"Bilan",sens:"Debit"},
  {numero:"352",libelle:"Produits B",classe:3,type:"Bilan",sens:"Debit"},
  // Classe 4
  {numero:"40",libelle:"Fournisseurs et comptes rattaches",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"401",libelle:"Fournisseurs d'exploitation",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"4011",libelle:"Fournisseurs - Achats de biens et prestations",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"402",libelle:"Fournisseurs d'investissements",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"408",libelle:"Fournisseurs - Factures non parvenues",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"41",libelle:"Clients et comptes rattaches",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"411",libelle:"Clients",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"4111",libelle:"Clients - Ventes de biens et prestations",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"416",libelle:"Clients douteux",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"418",libelle:"Clients - Factures a etablir",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"42",libelle:"Personnel",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"421",libelle:"Personnel - Avances et acomptes",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"422",libelle:"Commissions et courtages a payer",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"423",libelle:"Personnel - Remunerations dues",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"424",libelle:"Personnel - Oeuvres sociales",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"425",libelle:"Personnel - Oppositions sur salaires",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"427",libelle:"Personnel - Depots",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"43",libelle:"Organismes sociaux",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"431",libelle:"Securite sociale",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"432",libelle:"Caisses de retraite",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"438",libelle:"Autres organismes sociaux",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"44",libelle:"Etat et collectivites publiques",classe:4,type:"Bilan",sens:"Variable"},
  {numero:"441",libelle:"Etat - Subventions a recevoir",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"442",libelle:"Etat - Impots et taxes recouvrables",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"443",libelle:"Operations particulieres avec l'Etat",classe:4,type:"Bilan",sens:"Variable"},
  {numero:"444",libelle:"Etat - Impot sur le resultat",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"445",libelle:"Etat - TVA",classe:4,type:"Bilan",sens:"Variable"},
  {numero:"4451",libelle:"Etat - TVA facturee",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"4452",libelle:"Etat - TVA deductible sur achats",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"4454",libelle:"Etat - TVA a decaisser",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"4456",libelle:"Etat - TVA a recuperer",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"447",libelle:"Etat - Autres impots et taxes",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"46",libelle:"Debiteurs et crediteurs divers",classe:4,type:"Bilan",sens:"Variable"},
  {numero:"461",libelle:"Creances sur cessions d'immobilisations",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"462",libelle:"Creances sur cessions de titres",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"465",libelle:"Creances sur cessions de VMP",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"467",libelle:"Autres comptes debiteurs",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"4671",libelle:"Debiteurs divers",classe:4,type:"Bilan",sens:"Debit"},
  {numero:"468",libelle:"Divers crediteurs",classe:4,type:"Bilan",sens:"Credit"},
  {numero:"47",libelle:"Comptes transitoires ou d'attente",classe:4,type:"Bilan",sens:"Variable"},
  {numero:"471",libelle:"Comptes d'attente - Operations faites",classe:4,type:"Bilan",sens:"Variable"},
  {numero:"472",libelle:"Attente de regularisation",classe:4,type:"Bilan",sens:"Variable"},
  // Classe 5
  {numero:"50",libelle:"Titres de placement",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"501",libelle:"Parts dans des entreprises liees",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"502",libelle:"Actions",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"503",libelle:"Obligations",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"508",libelle:"Autres titres de placement",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"52",libelle:"Banques",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"521",libelle:"Banques locales",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"5211",libelle:"Banque X",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"5212",libelle:"Banque Y",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"522",libelle:"Banques autres",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"53",libelle:"Etablissements financiers et assimiles",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"531",libelle:"Cheques postaux",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"532",libelle:"Tresor",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"538",libelle:"Autres etablissements financiers",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"54",libelle:"Instruments de tresorerie",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"57",libelle:"Caisse",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"571",libelle:"Caisse siege social",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"572",libelle:"Caisse succursale A",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"573",libelle:"Caisse succursale B",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"58",libelle:"Regies d'avances, accreditifs et virements internes",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"581",libelle:"Regies d'avances",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"582",libelle:"Accreditifs",classe:5,type:"Bilan",sens:"Debit"},
  {numero:"585",libelle:"Virements de fonds",classe:5,type:"Bilan",sens:"Debit"},
  // Classe 6
  {numero:"60",libelle:"Achats et variations de stocks",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"601",libelle:"Achats de marchandises",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"602",libelle:"Achats de matieres premieres",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"604",libelle:"Achats stockes de matieres et fournitures",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"605",libelle:"Autres achats",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"61",libelle:"Transports",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"611",libelle:"Transports sur achats",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"612",libelle:"Transports sur ventes",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"614",libelle:"Transports du personnel",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"618",libelle:"Autres frais de transport",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"62",libelle:"Services exterieurs A",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"621",libelle:"Sous-traitance generale",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"622",libelle:"Locations et charges locatives",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"623",libelle:"Redevances de credit-bail",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"624",libelle:"Entretien, reparations et maintenance",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"625",libelle:"Primes d'assurances",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"626",libelle:"Etudes, recherches et documentation",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"627",libelle:"Publicite, publications et relations publiques",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"628",libelle:"Frais de telecommunications",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"63",libelle:"Services exterieurs B",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"631",libelle:"Frais bancaires",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"632",libelle:"Remunerations d'intermediaires et de conseils",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"633",libelle:"Frais de formation du personnel",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"634",libelle:"Redevances pour brevets, licences, logiciels",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"635",libelle:"Cotisations",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"637",libelle:"Remunerations de personnel exterieur",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"638",libelle:"Autres charges externes",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"64",libelle:"Impots et taxes",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"641",libelle:"Impots et taxes directs",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"642",libelle:"Impots et taxes indirects",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"645",libelle:"Autres impots et taxes",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"66",libelle:"Charges de personnel",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"661",libelle:"Appointements, salaires et commissions",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"662",libelle:"Primes et gratifications",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"663",libelle:"Indemnites de conges payes",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"664",libelle:"Charges sociales",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"665",libelle:"Autres charges sociales",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"667",libelle:"Remunerations transferees de charges",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"668",libelle:"Autres charges de personnel",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"67",libelle:"Frais financiers et charges assimilees",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"671",libelle:"Interets des emprunts",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"672",libelle:"Interets dans loyers de credit-bail",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"673",libelle:"Escomptes accordes",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"674",libelle:"Autres frais financiers",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"676",libelle:"Pertes de change",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"678",libelle:"Autres charges financieres",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"68",libelle:"Dotations aux amortissements",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"681",libelle:"Dotations aux amortissements d'exploitation",classe:6,type:"Gestion",sens:"Debit"},
  {numero:"687",libelle:"Dotations aux amortissements financiers",classe:6,type:"Gestion",sens:"Debit"},
  // Classe 7
  {numero:"70",libelle:"Ventes",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"701",libelle:"Ventes de marchandises",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"702",libelle:"Ventes de produits finis",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"703",libelle:"Ventes de produits intermediaires",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"704",libelle:"Ventes de produits residuels",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"706",libelle:"Prestations de services",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"707",libelle:"Produits accessoires",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"71",libelle:"Subventions d'exploitation",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"711",libelle:"Subventions d'equilibre",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"72",libelle:"Production immobilisee",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"721",libelle:"Immobilisations incorporelles",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"722",libelle:"Immobilisations corporelles",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"73",libelle:"Variations de stocks de biens et services produits",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"734",libelle:"Variation des en-cours",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"735",libelle:"Variation des stocks de produits",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"75",libelle:"Autres produits",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"754",libelle:"Ristournes percues",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"758",libelle:"Produits divers",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"77",libelle:"Revenus financiers et produits assimiles",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"771",libelle:"Interets de prets",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"772",libelle:"Revenus de participations",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"773",libelle:"Escomptes obtenus",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"776",libelle:"Gains de change",classe:7,type:"Gestion",sens:"Credit"},
  {numero:"778",libelle:"Autres produits financiers",classe:7,type:"Gestion",sens:"Credit"},
  // Classe 8
  {numero:"81",libelle:"Valeurs comptables des cessions d'immobilisations",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"811",libelle:"Immobilisations incorporelles",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"812",libelle:"Immobilisations corporelles",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"82",libelle:"Produits de cessions d'immobilisations",classe:8,type:"Gestion",sens:"Credit"},
  {numero:"821",libelle:"Immobilisations incorporelles",classe:8,type:"Gestion",sens:"Credit"},
  {numero:"822",libelle:"Immobilisations corporelles",classe:8,type:"Gestion",sens:"Credit"},
  {numero:"83",libelle:"Charges hors activites ordinaires",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"831",libelle:"Charges HAO constatees",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"84",libelle:"Produits hors activites ordinaires",classe:8,type:"Gestion",sens:"Credit"},
  {numero:"841",libelle:"Produits HAO constates",classe:8,type:"Gestion",sens:"Credit"},
  {numero:"85",libelle:"Dotations hors activites ordinaires",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"851",libelle:"Dotations aux amortissements HAO",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"87",libelle:"Participations des travailleurs",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"871",libelle:"Participation des travailleurs",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"89",libelle:"Impots sur le resultat",classe:8,type:"Gestion",sens:"Debit"},
  {numero:"891",libelle:"Impot sur le benefice",classe:8,type:"Gestion",sens:"Debit"},
];

// SYCEBNL-specific accounts (additions to SYSCOHADA for non-profit entities)
const PLAN_COMPTABLE_SYCEBNL_ADDITIONS = [
  {numero:"13",libelle:"Fonds dedies",classe:1,type:"Bilan",sens:"Credit",sycebnl:true},
  {numero:"131",libelle:"Fonds dedies projet A",classe:1,type:"Bilan",sens:"Credit",sycebnl:true},
  {numero:"132",libelle:"Fonds dedies projet B",classe:1,type:"Bilan",sens:"Credit",sycebnl:true},
  {numero:"133",libelle:"Fonds dedies projet C",classe:1,type:"Bilan",sens:"Credit",sycebnl:true},
  {numero:"45",libelle:"Donateurs et bailleurs de fonds",classe:4,type:"Bilan",sens:"Variable",sycebnl:true},
  {numero:"451",libelle:"Donateurs prives",classe:4,type:"Bilan",sens:"Debit",sycebnl:true},
  {numero:"452",libelle:"Bailleurs institutionnels",classe:4,type:"Bilan",sens:"Debit",sycebnl:true},
  {numero:"453",libelle:"Subventions a recevoir",classe:4,type:"Bilan",sens:"Debit",sycebnl:true},
  {numero:"454",libelle:"Cotisations a recevoir",classe:4,type:"Bilan",sens:"Debit",sycebnl:true},
  {numero:"74",libelle:"Dons et contributions",classe:7,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"741",libelle:"Dons en nature",classe:7,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"742",libelle:"Dons en especes",classe:7,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"743",libelle:"Subventions recues",classe:7,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"744",libelle:"Cotisations des membres",classe:7,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"745",libelle:"Legs et donations",classe:7,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"65",libelle:"Charges liees aux projets",classe:6,type:"Gestion",sens:"Debit",sycebnl:true},
  {numero:"651",libelle:"Depenses directes de projet",classe:6,type:"Gestion",sens:"Debit",sycebnl:true},
  {numero:"652",libelle:"Depenses indirectes de projet",classe:6,type:"Gestion",sens:"Debit",sycebnl:true},
  {numero:"653",libelle:"Missions et deplacements projet",classe:6,type:"Gestion",sens:"Debit",sycebnl:true},
];


// SYCEBNL Classe 9 — Contributions volontaires en nature (AUDCIF Art. 28)
const PLAN_COMPTABLE_SYCEBNL_CLASSE9 = [
  {numero:"91",libelle:"Contributions volontaires — emplois",classe:9,type:"Gestion",sens:"Debit",sycebnl:true},
  {numero:"910",libelle:"Benevoles — emplois valorises",classe:9,type:"Gestion",sens:"Debit",sycebnl:true},
  {numero:"911",libelle:"Mises a disposition de personnel",classe:9,type:"Gestion",sens:"Debit",sycebnl:true},
  {numero:"912",libelle:"Mises a disposition de biens",classe:9,type:"Gestion",sens:"Debit",sycebnl:true},
  {numero:"913",libelle:"Prestations de services gratuites",classe:9,type:"Gestion",sens:"Debit",sycebnl:true},
  {numero:"92",libelle:"Contributions volontaires — ressources",classe:9,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"920",libelle:"Benevoles — ressources valorisees",classe:9,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"921",libelle:"Contributions en personnel exterieur",classe:9,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"922",libelle:"Contributions en biens et services",classe:9,type:"Gestion",sens:"Credit",sycebnl:true},
  {numero:"923",libelle:"Dons en nature valorises",classe:9,type:"Gestion",sens:"Credit",sycebnl:true},
];

// Soldes d'ouverture (N-1) — indexes par numero de compte
const OPENING_BALANCES = {
  // SYSCOHADA demo — WASI Ecosystem SAS
  "101":  {n1d:0,       n1c:10000000},
  "111":  {n1d:0,       n1c:1200000},
  "121":  {n1d:0,       n1c:850000},
  "141":  {n1d:0,       n1c:3000000},
  "162":  {n1d:0,       n1c:15000000},
  "211":  {n1d:2500000, n1c:0},
  "244":  {n1d:4800000, n1c:0},
  "245":  {n1d:6200000, n1c:0},
  "281":  {n1d:0,       n1c:1200000},
  "284":  {n1d:0,       n1c:3100000},
  "401":  {n1d:0,       n1c:4200000},
  "411":  {n1d:3800000, n1c:0},
  "421":  {n1d:0,       n1c:920000},
  "444":  {n1d:0,       n1c:680000},
  "521":  {n1d:12500000,n1c:0},
  "571":  {n1d:450000,  n1c:0},
  // SYCEBNL demo — WASI Foundation
  "131":  {n1d:0,       n1c:8000000},
  "132":  {n1d:0,       n1c:2500000},
  "451":  {n1d:1200000, n1c:0},
  "452":  {n1d:3400000, n1c:0},
  "453":  {n1d:2100000, n1c:0},
  "920":  {n1d:0,       n1c:1200000},
  "910":  {n1d:1200000, n1c:0},
};
// Journal codes
const JOURNAL_CODES = [
  { code: "AC", label: "Journal des achats" },
  { code: "VT", label: "Journal des ventes" },
  { code: "BQ", label: "Journal de banque" },
  { code: "CA", label: "Journal de caisse" },
  { code: "OD", label: "Operations diverses" },
  { code: "AN", label: "A nouveaux" },
  { code: "EX", label: "Cloture exercice" },
  { code: "SA", label: "Journal des salaires" },
];

// Sample journal entries for demo
const SAMPLE_JOURNAL = [
  // Ecritures de demo — equilibrees
  {id:1,date:"2026-01-05",journal:"BQ",piece:"BQ-001",compte:"521",libelle:"Virement client WASI Corp",debit:5000000,credit:0,ref:"VIR-001"},
  {id:2,date:"2026-01-05",journal:"BQ",piece:"BQ-001",compte:"411",libelle:"Virement client WASI Corp",debit:0,credit:5000000,ref:"VIR-001"},
  {id:3,date:"2026-01-10",journal:"AC",piece:"FA-001",compte:"601",libelle:"Achat marchandises fournisseur Alpha",debit:2400000,credit:0,ref:"FA-2026-001"},
  {id:4,date:"2026-01-10",journal:"AC",piece:"FA-001",compte:"401",libelle:"Fournisseur Alpha — FA-2026-001",debit:0,credit:2400000,ref:"FA-2026-001"},
  {id:5,date:"2026-01-15",journal:"VT",piece:"FV-001",compte:"411",libelle:"Vente produits client Kofi Diallo",debit:3800000,credit:0,ref:"FV-2026-001"},
  {id:6,date:"2026-01-15",journal:"VT",piece:"FV-001",compte:"701",libelle:"Produits vendus — FV-2026-001",debit:0,credit:3800000,ref:"FV-2026-001"},
  {id:7,date:"2026-01-31",journal:"SA",piece:"SA-001",compte:"661",libelle:"Salaires janvier 2026",debit:1800000,credit:0,ref:"SA-2026-01"},
  {id:8,date:"2026-01-31",journal:"SA",piece:"SA-001",compte:"421",libelle:"Remuneration personnel janv. 2026",debit:0,credit:1800000,ref:"SA-2026-01"},
  {id:9,date:"2026-02-28",journal:"OD",piece:"OD-001",compte:"681",libelle:"Dotation amortissement materiel Q1",debit:420000,credit:0,ref:"INV-2026"},
  {id:10,date:"2026-02-28",journal:"OD",piece:"OD-001",compte:"284",libelle:"Amort. cumulee materiel Q1",debit:0,credit:420000,ref:"INV-2026"},
  {id:11,date:"2026-03-15",journal:"BQ",piece:"BQ-002",compte:"401",libelle:"Reglement fournisseur Alpha",debit:2400000,credit:0,ref:"BQ-2026-002"},
  {id:12,date:"2026-03-15",journal:"BQ",piece:"BQ-002",compte:"521",libelle:"Debit banque — fournisseur Alpha",debit:0,credit:2400000,ref:"BQ-2026-002"},
];

// OHADA financial statement blocks
const BILAN_STRUCTURE = {
  actif: [
    { section: "ACTIF IMMOBILISE", accounts: [21,22,23,24], amort: [28], note: "Valeur brute moins amortissements" },
    { section: "ACTIF CIRCULANT", accounts: [31,32,33,35,41,42,44,46], note: "Stocks + Creances" },
    { section: "TRESORERIE ACTIF", accounts: [50,52,53,54,57,58], note: "Banques + Caisse + VMP" },
  ],
  passif: [
    { section: "CAPITAUX PROPRES", accounts: [10,11,12,13,14], note: "Capital + Reserves + Resultat" },
    { section: "DETTES FINANCIERES", accounts: [16], note: "Emprunts et dettes a long terme" },
    { section: "PASSIF CIRCULANT", accounts: [40,42,43,44,46,47], note: "Fournisseurs + Personnel + Etat" },
    { section: "TRESORERIE PASSIF", accounts: [56], note: "Decouverts et credits de tresorerie" },
  ]
};

const RESULTAT_STRUCTURE = [
  { section: "CHIFFRE D'AFFAIRES", comptes: ["70"], sens: "credit" },
  { section: "AUTRES PRODUITS", comptes: ["71","72","73","75"], sens: "credit" },
  { section: "ACHATS", comptes: ["60"], sens: "debit" },
  { section: "TRANSPORTS", comptes: ["61"], sens: "debit" },
  { section: "SERVICES EXTERIEURS", comptes: ["62","63"], sens: "debit" },
  { section: "IMPOTS ET TAXES", comptes: ["64"], sens: "debit" },
  { section: "CHARGES DE PERSONNEL", comptes: ["66"], sens: "debit" },
  { section: "DOTATIONS AUX AMORTISSEMENTS", comptes: ["68"], sens: "debit" },
  { section: "PRODUITS FINANCIERS", comptes: ["77"], sens: "credit" },
  { section: "CHARGES FINANCIERES", comptes: ["67"], sens: "debit" },
  { section: "PRODUITS HAO", comptes: ["82","84"], sens: "credit" },
  { section: "CHARGES HAO", comptes: ["81","83","85"], sens: "debit" },
  { section: "PARTICIPATION TRAVAILLEURS", comptes: ["87"], sens: "debit" },
  { section: "IMPOT SUR LE RESULTAT", comptes: ["89"], sens: "debit" },
];

// SYCEBNL Compte de Resultat — structure officielle PAO / CAO
const RESULTAT_SYCEBNL_STRUCTURE = {
  pao: [
    {ref:"RA",label:"Cotisations et contributions des membres",comptes:["744"],sens:"credit"},
    {ref:"RB",label:"Dons en especes et legs",comptes:["742"],sens:"credit"},
    {ref:"RC",label:"Dons en nature valorises",comptes:["741"],sens:"credit"},
    {ref:"RD",label:"Subventions de fonctionnement recues",comptes:["711"],sens:"credit"},
    {ref:"RE",label:"Subventions de projets recues",comptes:["743"],sens:"credit"},
    {ref:"RF",label:"Produits de la vente de biens et services",comptes:["701","706"],sens:"credit"},
    {ref:"RG",label:"Revenus financiers",comptes:["77"],sens:"credit"},
    {ref:"RH",label:"Produits HAO",comptes:["82","84"],sens:"credit"},
    {ref:"RI",label:"Autres produits",comptes:["75","72"],sens:"credit"},
  ],
  cao: [
    {ref:"EA",label:"Achats de biens et fournitures",comptes:["601","604","605"],sens:"debit"},
    {ref:"EB",label:"Transports et deplacements",comptes:["61","653"],sens:"debit"},
    {ref:"EC",label:"Services exterieurs",comptes:["62","63"],sens:"debit"},
    {ref:"ED",label:"Charges liees aux projets",comptes:["651","652"],sens:"debit"},
    {ref:"EE",label:"Impots et taxes",comptes:["64"],sens:"debit"},
    {ref:"EF",label:"Charges de personnel",comptes:["66"],sens:"debit"},
    {ref:"EG",label:"Dotations aux amortissements",comptes:["68"],sens:"debit"},
    {ref:"EH",label:"Charges financieres et HAO",comptes:["67","81","83","85","87","89"],sens:"debit"},
  ]
};

// OHADA member states
const OHADA_MEMBER_STATES = [
  "Benin", "Burkina Faso", "Cameroun", "Centrafrique", "Comores", "Congo",
  "Cote d'Ivoire", "Gabon", "Guinee", "Guinee-Bissau", "Guinee equatoriale",
  "Mali", "Niger", "RD Congo", "Senegal", "Tchad", "Togo"
];

// Guide content
const OHADA_GUIDE = {
  title: "Guide OHADA — Droit Comptable et Information Financiere",
  sections: [
    {
      title: "Qu'est-ce que l'OHADA ?",
      content: "L'Organisation pour l'Harmonisation en Afrique du Droit des Affaires (OHADA) est un systeme juridique adopte par 17 pays africains pour harmoniser le droit des affaires. L'Acte Uniforme relatif au droit comptable et a l'information financiere (AUDCIF) definit les regles comptables applicables."
    },
    {
      title: "SYSCOHADA Revise (2017)",
      content: "Le Systeme Comptable OHADA revise est entre en vigueur le 1er janvier 2018 pour les comptes personnels et le 1er janvier 2019 pour les comptes consolides. Il s'applique a toutes les entites a but lucratif des 17 Etats membres."
    },
    {
      title: "SYCEBNL",
      content: "Le Systeme Comptable des Entites a But Non Lucratif (SYCEBNL) s'applique aux associations, ONG, fondations, partis politiques, syndicats et autres entites sans but lucratif. Il partage la structure SYSCOHADA avec des adaptations specifiques (fonds dedies, donateurs, cotisations)."
    },
    {
      title: "Etats financiers obligatoires",
      content: "Le systeme normal OHADA exige: 1) Bilan, 2) Compte de resultat, 3) TAFIRE (Tableau Financier des Ressources et Emplois), 4) Notes annexes. Le systeme minimal de tresorerie (SMT) est reserve aux tres petites entites."
    },
    {
      title: "Principes comptables OHADA",
      content: "Les principes fondamentaux sont: prudence, permanence des methodes, cout historique, specialisation des exercices, continuite de l'exploitation, importance significative, preminence de la realite sur l'apparence, intangibilite du bilan d'ouverture."
    },
    {
      title: "Cadre reglementaire",
      content: "Le referentiel inclut: l'Acte Uniforme AUDCIF, le Plan Comptable General OHADA, le Guide d'Application SYSCOHADA, les dispositions fiscales nationales (DSF/DGI), et les normes d'audit OHADA."
    },
  ]
};
